# syntax=docker/dockerfile:1
FROM ghcr.io/yingquelou/alpine:3.24.2
RUN apk update
RUN apk add doas
RUN cat > /etc/doas.d/doas.conf <<'EOF'
permit persist :wheel
EOF
RUN apk add nodejs pnpm
ENTRYPOINT sh